# Generated by Django 5.1.6 on 2025-02-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="fecha_publicacion",
        ),
        migrations.RemoveField(
            model_name="libro",
            name="paginas",
        ),
        migrations.RemoveField(
            model_name="libro",
            name="sinopsis",
        ),
    ]
